Fix note list toggle
Automattic/simplenote-electron pull request #2037
Opened 2020-04-24 04:52 UTC by codebykat

### Fix
When we refactored the previousIndex and note list toggle, we didn't account for behavior on small screens. This PR disentangles that by clarifying when we want `CLOSE_NOTE` (unselect the selected note) and when we want `TOGGLE_NOTE_LIST` (keep a note selected, but switch to list view).

This has the interesting side effect of making it possible to maintain a selected note on the small screen. I removed the check that disables the selected note highlight on small views. You can now use the note list keyboard command to toggle between list and note view without losing the selected note, and use next/previous note from either view to select and open a new note.

This will fix #2029 

### Todo
When loading the app on a narrow screen, it's not selecting the note list by default, so it's a blank screen until you use the keyboard combo to show the note list, after which everything works.

### Test
1. Load the app on a narrow window
2. Use the keyboard command to toggle the note list
3. Select a note and ensure the note shows
4. Ensure the back button on the note takes you back to the note list

### Release
Not updated: Fix a bug that prevented being able to access the note list on small screens

2020-04-27 16:52 UTC, belcherj requested changes

2020-04-27 16:52 UTC, belcherj commented on lib/note-content-editor.tsx
> +    console.log(this.props.editingEnabled);
Remove console.log

2020-04-27 16:52 UTC, belcherj commented on lib/note-detail/index.tsx
> +      isSmallScreen,
I don't think this is needed due to https://github.com/Automattic/simplenote-electron/pull/2037/files#diff-52e457c4f342fbeecf796739f2492ccaR385

2020-04-27 16:52 UTC, belcherj commented on lib/note-editor/index.tsx
> +          isSmallScreen={isSmallScreen}
I don't think this is needed due to https://github.com/Automattic/simplenote-electron/pull/2037/files#diff-52e457c4f342fbeecf796739f2492ccaR385

2020-04-28 00:22 UTC, codebykat commented
Addressed the review comments and I think this is looking great! Maintaining the currently selected note and using `Enter` to open into note view feels really slick. I think this a lot more usable than it was before honestly.

I have one really minor edge case, which is that on first load in wide screen, a note is seemingly selected (the first note is in the editor window), but if you resize the window to narrow screen, you get the note list. If you instead select a note first and then resize, it sticks with the note view. I think this is probably fine since the user hasn't actively selected a note yet, but it's a little inconsistent.

2020-04-28 13:24 UTC, belcherj approved these changes
Ship It!

2020-04-28 19:20 UTC, merged