Enable system theme for Electron builds
Automattic/simplenote-electron pull request #2135
Opened 2020-06-04 06:18 UTC by codebykat

### Fix

When we added System theme (follow OS light/dark setting), the version of Electron didn't support it. As of Electron 7.0.0, it seems that it does:

https://www.electronjs.org/docs/tutorial/mojave-dark-mode-guide

This PR enables the System theme setting in both the menu bar and Settings dialog.

Will fix #2134 

### Test

1. Set Electron to "System" theme and verify that it changes to whatever the OS is set to
2. Change the OS setting and verify that Electron also changes to follow
3. Use the light/dark themes and make sure they don't change
4. We need to test this on Windows and Linux! I am not sure of the cross-platform support or if we need to be special-casing it.

### Review

It looks to me like we're not following the docs here and accessing this property via Electron's `nativeTheme` API:

https://www.electronjs.org/docs/api/native-theme

However, what we're doing appears to work fine, at least on OSX. Possibly @belcherj knows more.

### Release

Not updated: Add System theme for Electron builds

2020-06-04 14:02 UTC, belcherj commented
This does not work in Windows. I think we will need to do some more work on Windows and Linux.

2020-06-09 16:14 UTC, belcherj requested changes
Could you take a look at Windows and Linux?

2020-07-16 11:20 UTC, stpoa commented
I need this one for mac :) If there is a problem for other platforms, can you split this pr to just support macos?

2021-04-30 21:09 UTC, codebykat commented
Superseded by #2882

2021-04-30 21:09 UTC, closed without merging