User browser for authing a user via WP Login
Automattic/simplenote-electron pull request #2147
Opened 2020-06-10 17:58 UTC by belcherj

See p2XJRt-1Y0-p2

### Fix

In order to pass the Windows store certification, we cannot do auth in the app. Instead, it needs to be pushed to a browser.

There is still uncertainty that this will resolve the issue with certification however this is the only solution that I can see as a path forward.

### Test

1. Run app
2. In Electron click the WordPress.com login button
3. Log in
4. Were you able to log in?

2020-06-10 18:01 UTC, dmsnell commented on desktop/app.js
> +  }
is this part of the same fix or is this a secondary fix?

2020-06-10 18:02 UTC, dmsnell commented on electron-builder.json
> +    "schemes": ["simplnote"]
typo: `simplnote` → `simplenote`

2020-06-10 18:02 UTC, dmsnell commented on lib/auth/index.tsx
> +      debugger;
noting to remove later

2020-06-10 18:03 UTC, belcherj commented on desktop/app.js
> +  }
This is part of the fix

2020-06-10 18:03 UTC, dmsnell commented
Can you explain more what the problem is and how this resolves it?

Is the problem that we create a second window to handle auth whereas replacing the app itself with loading the WP login solves the issue?

2020-06-10 18:03 UTC, belcherj commented on electron-builder.json
> +    "schemes": ["simplnote"]
Ohhhh jeez

2020-06-10 18:05 UTC, belcherj commented
The issue is that we cannot use a window inside the app to do WordPress.com login because it violates the Microsoft store policy for certification.  We need to do it in the browser.

2020-06-10 18:08 UTC, dmsnell commented on desktop/app.js
> +  }
can you maybe explain this more and explain why we have to set this here? (in a comment)

2020-06-10 18:10 UTC, belcherj commented on desktop/app.js
> +  }
We have to set a custom simplenote:// protocol so when the browser gets the callback URL from WordPress.com it deep links into the app.

2020-06-10 18:14 UTC, dmsnell commented on lib/auth/index.tsx
> +    shell.openExternal(authUrl);
won't this cause issues for in-browser views or does the Electron code work in the browser context too?

2020-06-10 18:17 UTC, belcherj commented on desktop/app.js
> +  }
Comment added

2020-06-10 18:17 UTC, dmsnell commented
> we cannot use a window inside the app to do WordPress.com login

thanks. did we confirm that this change resolves their issue? I know App Store rules can seem bureaucratic but it definitely feels like we're doing the same thing here - did they provide a link to their rules documentation?

The interface inside of `lib/auth/index` also feels a bit ad-hoc or convenient. I know we're wanting to hurry to get it in the store but I wonder if we shouldn't isolate that more in a separate module or at least provide clear documentation in the comments what's happening and where/how the signals are coming from the external window.

Also, what is supposed to happen if we don't complete the auth process in the external window? When I read the code it looks like we should always be sending `wpLogin` based on `desktop/app.js` and in `auth/index` it looks like we should only receive the `wpLogin` message after the WPCC process is done?

Mainly I'm saying that I'm confused reading the code and the login flow is hard for me to figure out.

2020-06-10 18:19 UTC, belcherj commented on lib/auth/index.tsx
> +    shell.openExternal(authUrl);
This code never gets rendered in the browser, except for in dev. Will add back code from L181

2020-06-10 18:44 UTC, belcherj commented
This is the 'get it working' stage of this PR. I need to do some cleanup work for sure.

We are doing the same thing but not in app, we are doing it in the browser. If this does not fix the issue for certification then we will likely have to remove WordPress.com login from the app that gets submitted to the MS app store.

2020-06-10 18:57 UTC, dmsnell commented
> If this does not fix the issue for certification then we will likely have to remove WordPress.com login from the app that gets submitted to the MS app store.

Do they provide a way for us to know this before we change the code? Do they link to the guidelines that they argue we violate?

2020-06-10 19:10 UTC, belcherj commented
I asked via email.

https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies

These are the two non-compliance issues: 

10.1.5 Software Distribution
10.8.2 In-App Purchase: Physical Goods & Services

There is no way to tell if this will comply.

2020-06-10 19:19 UTC, dmsnell commented
> 10.1.5 Software Distribution
> 10.8.2 In-App Purchase: Physical Goods & Services

It sounds like they don't understand the role of the WordPress.com signin since those rules apply to purchases or other software. How does opening in an external window address these?

> There is no way to tell if this will comply.

Do they not respond to the email or just say "submit again and see if it works." Seems like we wouldn't be the only ones having this issue and I wonder if there's something we could do to get their attention to give an adequate review.

It doesn't seem like Simplenote login and WP login are any different based on their qualifications. I guess they should be blocking us if we were trying to allow people to login with their Live accounts too?

2020-06-11 17:23 UTC, belcherj commented
> It sounds like they don't understand the role of the WordPress.com signin since those rules apply to purchases or other software. How does opening in an external window address these?

Once you pop open the auth window you can navigate on Apple and Google website which allow for purchases within the app.

By sending them to a browser window they would not be able to make purchases within the app.

2020-07-07 18:37 UTC, codebykat requested changes
I don't know what's up but I'm getting a white screen on Electron with `npm run dev`. I deleted my `node_modules` and did a full `npm install` several times. No errors in the console.

2020-07-07 18:57 UTC, codebykat approved these changes
Okay the build thing was unrelated (due to having been on the rewrite branch and not clearing site data).

This is not ideal but it's fine for now so we can get the release process unblocked.

Clicking "Log in with WordPress.com" runs validation on the form, causing this field to pop up:

<img width="425" alt="Screen Shot 2020-07-07 at 11 54 58 AM" src="https://user-images.githubusercontent.com/52152/86828937-b419f600-c048-11ea-964a-be478a70fdc8.png">

Got this when returning from the browser, in the standalone build does it say Simplenote rather than Electron?

<img width="300" alt="Screen Shot 2020-07-07 at 11 52 56 AM" src="https://user-images.githubusercontent.com/52152/86829025-ceec6a80-c048-11ea-87dc-f1ab38f7c5a7.png">

2020-07-07 19:26 UTC, belcherj commented
Closing in favour of https://github.com/Automattic/simplenote-electron/pull/2191

2020-07-07 19:26 UTC, closed without merging