Make tags in tag list links until they are being edited
Automattic/simplenote-electron pull request #2352
Opened 2020-09-22 20:18 UTC by belcherj

### Fix

Closes: https://github.com/Automattic/simplenote-electron/issues/844

In the tag navigation panel, tags are represented as inputs even when not editing.

There are two problems with this:

- It is unsemantic HTML and not good for accessibility.
- An Undo/Redo context menu will be shown on right click, which doesn't make sense for links.

This PR makes them links as they should.

### Test
1. Open chrome dev tools.
2. Inspect tags in the tag list, they should be link tags
3. Ensure that they render correctly
4. Ensure that the selected tag gets rendered correctly
5. Ensure that you can edit a tag

2020-09-22 21:51 UTC, dmsnell reviewed
If we're not going to use `<button>` or `<input type="button">` (which seem to be [the preferred mechanisms](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)) then we should at least add in `role="button"` and for the link tag a `href`, I think.

It seems reasonable that styling could prevent us from using the preferred tags. In this case a link seems appropriate but I am far from an authority on accessibility. I also know that this is not an exception in the app and a little better accessibility is going to be better than less.

2020-09-22 21:54 UTC, codebykat requested changes
This is introducing a horizontal scroll with long tag names that isn't present in production:

<img width="221" alt="Screen Shot 2020-09-22 at 2 43 11 PM" src="https://user-images.githubusercontent.com/52152/93940782-f5ce4a80-fce1-11ea-8b92-bed178649752.png">

It's also stripping the leading spaces from a test tag I happened to have that has leading spaces... good or bad, I don't know. Different than production. We should be stripping these whitespace characters out anyway, but maybe not here. The spaces do show up in edit mode.

<img width="217" alt="Screen Shot 2020-09-22 at 2 52 34 PM" src="https://user-images.githubusercontent.com/52152/93941526-83f70080-fce3-11ea-9baa-ad898d3324a3.png">
<img width="223" alt="Screen Shot 2020-09-22 at 2 52 37 PM" src="https://user-images.githubusercontent.com/52152/93941533-86f1f100-fce3-11ea-9b1d-f4f4c3640fa0.png">


Non-blocker... this incidentally breaks something that maybe shouldn't work, but does: in production you can currently right-click a tag and "select all" to select the tag.

In this PR in Electron, selecting all seems to do nothing, but when you switch to Edit mode, all tags are selected. In Firefox it just does nothing (more fine).

It is not possible to drag the mouse cursor over a tag name (here or in production) in order to copy the text, if desired. The only way to copy a tag name would be to enter Edit mode.

I just found a bug with dragging-and-dropping tag names but it's present in production too 🤦‍♀️

2020-10-02 13:51 UTC, belcherj commented
This is ready for review

2020-10-02 18:44 UTC, dmsnell approved these changes
Thanks for the updates. This was always weird and I think this makes it better. At some point we probably want to do something better with finishing the tag-name edit session (I think right now it's just an `onBlur`). One step at a time though 👍

2020-10-02 18:44 UTC, merged