feat(slider): aria-label
Automattic/simplenote-electron pull request #2583
Opened 2021-01-16 22:37 UTC by tbourrely

### Fix

### Test

1.
2.
3.

### Release

2021-01-16 22:38 UTC, tbourrely commented
This should resolve #1396

2021-01-21 12:11 UTC, sandymcfadden requested changes
Thanks so much for submitting this!
While taking a closer look we can make this even easier. This is the only instance of us using the Slider component and I don't see any other times currently that we may use it elsewhere. With that, we can instead add the `aria-label` directly to the input without the need of passing in the text for the label as Props. 

If you want to update to that we can get this merged.

2021-01-23 08:53 UTC, tbourrely commented
Done 🙂

2021-01-25 14:45 UTC, sandymcfadden approved these changes
Looks good. Thanks so much!

2021-01-25 14:47 UTC, merged

2021-01-28 15:38 UTC, pachlava commented
[testing] Confirm that slider input now has a new 'aria-label' attribute, with "Select revision" value
Win10 | desktop SN 2.6.0-beta1