Update the revision slider so that it does not cover the bottom of long notes
Automattic/simplenote-electron pull request #2662
Opened 2021-02-11 15:25 UTC by sandymcfadden

### Fix

With the update to the slider position, it was sitting over top the bottom of long notes. So you couldn't see changes happening at the end no matter how far you scrolled.

This resolves #2655

### Test

1. Have a note with enough content that fills the editor.
2. Open the history for the note.
3. Ensure you can scroll and see all the note content.

### Release

- Fix the revision slider so that the full note is visible.

2021-02-11 21:51 UTC, codebykat approved these changes
Looks good. I think this should also be a hotfix against release/2.7.0. I'll leave the rebase to you for practice :)

2021-02-12 00:10 UTC, codebykat requested changes
Oh also when you rebase against release/2.7.0 don't forget to add a line to the release notes :) (Just setting as Changes Requested to make sure you see this)

2021-02-12 12:21 UTC, sandymcfadden commented
@codebykat you were right about me needing the practice. It looks like I still need more and that I messed this up again.

2021-02-12 17:40 UTC, sandymcfadden commented
Thanks so much, @belcherj for helping me get this PR fixed up with the git lesson.

2021-02-16 23:14 UTC, codebykat commented
> Also, I'm not sure I need to add anything to the release notes as there is already a line about updating the revision slider? Let me know what you think.

Yeah, fair. So what I would do is edit the release notes to add a link to this PR as well. You can see prior examples where we had more than one PR linked for a single line.

Nice work on the git fix! I love that JB and I have totally different methods of resolving that issue. Git: There is always more than one correct way to shoot yourself in the foot. 😂

2021-02-18 12:39 UTC, sandymcfadden commented
Thank you @codebykat! I've updated the release notes now.

2021-02-18 23:10 UTC, codebykat approved these changes

2021-02-18 23:11 UTC, merged

2021-02-18 23:57 UTC, mokagio commented
Thanks @codebykat 🙌 !