Fix the alignment of new note icon in focus mode
Automattic/simplenote-electron pull request #2671
Opened 2021-02-12 11:53 UTC by sandymcfadden

### Fix

When adding in the new note icon in focus mode the alignment did not fit with the other icons.
This PR aligns it better.
Also on Mac Electron only it removes the dividing line between the focus mode icon and the new note icon when in focus mode. It did not work well and overlapped the Mac window buttons. 
Spoke with @SylvesterWilmott about it removing the dividing line here seemed like the best option.
Resolves #2658

macOS Electron
<img width="342" alt="Screen Shot 2021-02-12 at 7 51 44 AM" src="https://user-images.githubusercontent.com/1326294/107764884-4bde7180-6d07-11eb-8ecf-a31051bdf058.png">

Browser
![Screen Shot 2021-02-12 at 7 52 25 AM](https://user-images.githubusercontent.com/1326294/107764906-5567d980-6d07-11eb-8175-4bd5b22077d1.png)

### Test

1. Open focus mode on macOS Electron.
2. Ensure the dividing line between the new note and the focus mode does not appear.
3. Ensure the icons are aligned properly.
4. Ensure icons align properly in browsers as well.

### Release

2021-02-15 10:37 UTC, SylvesterWilmott commented
LGTM

Thanks @sandymcfadden

2021-02-16 22:44 UTC, codebykat commented
I've been staring at this for far too long and I feel like something is still funny, I don't know why.

Inspector in Firefox tells me the top toolbar is getting a height of 43px, not 44px. Is it getting flexed?

<img width="314" alt="Screen Shot 2021-02-16 at 2 41 23 PM" src="https://user-images.githubusercontent.com/52152/108130780-0f8f7600-7065-11eb-9a63-602070268ad3.png">

I can't tell if the New Note button is actually like a single pixel too low or if it's just the way that icon is sized compared to the other one. And why is this span 17px height??
  
<img width="150" alt="Screen Shot 2021-02-16 at 2 34 58 PM" src="https://user-images.githubusercontent.com/52152/108130646-d9ea8d00-7064-11eb-815e-504c97d830a8.png">

<img width="253" alt="Screen Shot 2021-02-16 at 2 34 26 PM" src="https://user-images.githubusercontent.com/52152/108130669-e1aa3180-7064-11eb-9f23-3055d0deebfa.png">

The button element is not centered for the new note icon, I feel like this has something to do with it.

<img width="126" alt="Screen Shot 2021-02-16 at 2 43 22 PM" src="https://user-images.githubusercontent.com/52152/108130970-609f6a00-7065-11eb-81fb-56a0b87f3c8b.png">

<img width="209" alt="Screen Shot 2021-02-16 at 2 43 16 PM" src="https://user-images.githubusercontent.com/52152/108130978-64cb8780-7065-11eb-838b-960f4295c851.png">

2021-02-16 23:08 UTC, codebykat requested changes
I messed around with this in inspector a bit and it looks like it works to put a `margin-top: 6px` on the `icon-button` container for the new note button (toolbar height of 44px - icon button height of 32px = 12px, divided by 2). I then also needed to set `vertical-align: baseline` on the `svg` just for that button (it's inheriting `vertical-align: middle`, which is what the other toolbar icons need, but apparently not this one).

<img width="145" alt="Screen Shot 2021-02-16 at 3 05 41 PM" src="https://user-images.githubusercontent.com/52152/108133059-c7725280-7068-11eb-9665-697adb8f0f70.png">

p.s. Since this is a hotfix, this also needs release notes please!

2021-02-16 23:10 UTC, codebykat commented
BTW All of the above was in Firefox, it may need an extra padding on OSX to account for the additional toolbar padding.

2021-02-18 13:36 UTC, sandymcfadden commented
Wow thank you so much @codebykat. I looked at this for a long time as well and tried a bunch of things. I think the `vertical-align: baseline;` is what I missed when I was working on this to get things to work right.

2021-02-18 23:20 UTC, codebykat approved these changes

2021-02-18 23:20 UTC, merged

2021-02-18 23:56 UTC, mokagio commented
Thanks @codebykat 🙌