[WIP] fix ctrl+G on Windows
Automattic/simplenote-electron pull request #2705
Opened 2021-03-02 06:39 UTC by codebykat

Pushing this up to get a testable Windows build, please ignore

2021-03-03 12:02 UTC, sandymcfadden requested changes
I've been testing on Linux and the only one that doesn't seem to be working as expected is the open tag list `Ctrl + Shift + U`. If you are focused on the editor this doesn't fire while all others seem to.

It does work on the Mac build as expected. Should this be moved into the `handleBrowserShortcut` function?

2021-03-04 07:13 UTC, codebykat commented
> I've been testing on Linux and the only one that doesn't seem to be working as expected is the open tag list `Ctrl + Shift + U`. If you are focused on the editor this doesn't fire while all others seem to.

Hmm. It works on Windows for me, regardless of what has focus.

Are you on Ubuntu? Is it possible Ubuntu is eating it? https://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux

Also, how does this compare to the functionality in the 2.7.0 and/or 2.6.0 releases? I don't know if this shortcut gets much use, so maybe it's never worked properly..

2021-03-09 11:38 UTC, sandymcfadden commented
You're right this seems to be the case that it is a global keyboard shortcut on some versions of Linux. I tried on 2.6.0 and had the same issue. Should we look at changing this shortcut, or be OK with it not working on Linux?

2021-03-10 02:04 UTC, codebykat commented
I'm going to merge this for 2.8.0 to get the Windows shortcuts fixed, and open a follow-up issue. Thanks @sandymcfadden!

2021-03-10 02:04 UTC, merged