2.9.0 release notes
Automattic/simplenote-electron pull request #2794
Opened 2021-03-21 12:32 UTC by sandymcfadden

Draft: Parent branch should be `release/2.9.0`

https://github.com/Automattic/simplenote-electron/milestone/50?closed=1

2021-03-22 22:21 UTC, codebykat commented
Set this back to "draft" pending a confirmation against commit comparison to make sure nothing was missed. (Link added to the description)

2021-03-24 10:53 UTC, sandymcfadden commented
Gone through and confirmed all the commits. Had to add one to the release notes that was missed previously.

2021-03-27 21:57 UTC, codebykat requested changes
This is nitpicky, but can we go through and make them all the same tense? I think I usually go with past tense. This current version has every variation imaginable (Made / Removes / Improved / Updating) and it's hard to scan.

2021-03-29 10:50 UTC, sandymcfadden commented
Thanks @codebykat I have that updated now.

2021-03-30 19:04 UTC, codebykat approved these changes

2021-03-30 19:06 UTC, merged