Add default title bar space for Mac Electron
Automattic/simplenote-electron pull request #2896
Opened 2021-05-04 16:39 UTC by sandymcfadden

### Fix

Previously we had been adding specific styles to different components for only Mac Electron app to prevent things from overlapping the window buttons.

This removes those and instead enables the default title bar.

### Test

1. Run Mac Electron app.
2. Ensure bar appears at the top with the app below it as usual.

### Release

- Added default title bar to Mac Electron app

2021-05-04 16:59 UTC, belcherj requested changes
Looks good except:

- note-toolbar/style.scss Line 22

It looks a little different. Can you get a review from Sly? We don't ship macOS so It is more of making him aware.

2021-05-04 17:09 UTC, sandymcfadden commented
Thanks, @belcherj I was so confused because while searching in my editor I couldn't find any more instances of `is-macos`. There wasn't any, but I hadn't saved that file after changing 🤦

2021-05-05 08:30 UTC, SylvesterWilmott commented
Looks good @sandymcfadden

2021-05-05 17:04 UTC, belcherj approved these changes
Ship

2021-05-05 17:30 UTC, merged