Update Dark mode colors to use to css variables
Automattic/simplenote-electron pull request #2936
Opened 2021-06-22 11:22 UTC by sandymcfadden

### Fix

This is a continuation of previous work to update the CSS to use variables for colors.
This moves all colors for dark mode to use CSS variables instead. 

There should be no user impact or any noticeable changes. It's an intermediate step to simplifying the CSS used throughout the app. 

### Test

1. Smoke test in dark mode
2. Ensure that everything looks good

### Release

- Update colors in dark mode to use CSS variables

2021-06-25 00:30 UTC, codebykat requested changes
Phew that's a lot of files changed 😂

It looks pretty good to me. I did note one difference in comparing this build to what's currently on app.simplenote.com, a slight change in the text colors in some of the Settings panels. It's visible on Collaborate (the text color got brighter while the example text in the form field got dimmer) and also on the analytics informational text in Settings.

app.simplenote.com:

<img width="413" alt="Screen Shot 2021-06-24 at 5 21 54 PM" src="https://user-images.githubusercontent.com/52152/123351045-282b0380-d511-11eb-80f0-b451572b3fee.png">

<img width="397" alt="Screen Shot 2021-06-24 at 5 24 10 PM" src="https://user-images.githubusercontent.com/52152/123351390-d8990780-d511-11eb-8d0e-525cc5b98462.png">

this branch in browser:

<img width="431" alt="Screen Shot 2021-06-24 at 5 21 58 PM" src="https://user-images.githubusercontent.com/52152/123351054-2f521180-d511-11eb-8ce2-7b5248d58026.png">

<img width="394" alt="Screen Shot 2021-06-24 at 5 24 12 PM" src="https://user-images.githubusercontent.com/52152/123351396-ddf65200-d511-11eb-918e-c5ade60f3b2b.png">


The "Move to trash" link in the dropdown has also changed.

app.simplenote.com:

<img width="227" alt="Screen Shot 2021-06-24 at 5 26 01 PM" src="https://user-images.githubusercontent.com/52152/123351114-5577b180-d511-11eb-9045-b966a2e6c85f.png">

this branch in browser:


<img width="229" alt="Screen Shot 2021-06-24 at 5 26 05 PM" src="https://user-images.githubusercontent.com/52152/123351107-50b2fd80-d511-11eb-960d-22057c30c943.png">

2021-06-25 14:01 UTC, sandymcfadden commented
Thanks so much @codebykat This is a lot of changes the next PRs that follow this will be much more manageable. 

- For the placeholder text on the collaborate screen I do see it the difference, I think we should leave it as in this PR though, it matches the login form inputs. What do you think @SylvesterWilmott?
- I've fixed up the text on the settings panels
- I see what you mean about the Move to trash button as well. I used the same color here that was used on the delete forever button when in the Trash. It kind of makes sense to me that those destructive buttons should match. What do you think of this one too @SylvesterWilmott?

2021-06-28 08:40 UTC, SylvesterWilmott commented
Thanks for spotting those @codebykat 

> For the placeholder text on the collaborate screen I do see it the difference, I think we should leave it as in this PR though, it matches the login form inputs.

In this case, the placeholder text in dark mode should be gray20. As time goes on I would prefer to use transparency over colours since dark mode will contain a lot of different surface colours and we will need to make sure that all input states have sufficient contrast. For now, can we update the instances where the placeholder text is not gray20.

> It kind of makes sense to me that those destructive buttons should match.

For sufficient contrast, coloured text should be the [color]20 version. So in this case, any red text on a dark background should be red20 so we should update the "Delete forever" label.

It may be helpful if I reiterate the color rules on text here:

**Light mode:**

Primary text: Gray80
Secondary text: gray50
Coloured text: [color]50
Placeholder text: gray50

**Dark mode:**

Primary text: White
Secondary text: gray20
Coloured text: [color]20
Placeholder text: gray20

2021-06-28 09:39 UTC, sandymcfadden commented
Thank you @SylvesterWilmott that's very helpful. I believe I have everything updated appropriately now.

2021-06-28 10:11 UTC, SylvesterWilmott approved these changes
:shipit:  if we spot any more inconsistencies we can fix as we go.

2021-06-28 10:21 UTC, merged